name: List Updated Directories
on: 
  push:
    branches:
      - main  # Adjust this to your branch name if different
jobs:
  list-updated-directories:
    runs-on: ubuntu-latest  # Specify the machine type
      
    steps:

    - name: Get a list of directories with updated files
      id: install-cmipld
      uses: WCRP-CMIP/CMIP-LD/actions/cmipld@main
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get a list of directories with updated files
      id: updated-dirs
      uses: WCRP-CMIP/CMIP-LD/actions/updated_dirs@main

    - name: Compile JSONLD files, generate an RDF network and update frames
      id: jsonld
      uses: WCRP-CMIP/CMIP-LD/actions/jsonld@main
      with:
        dirs: ${{ env.updated_dirs }}
        frames: "$PWD/compiled/graph_data.json"


    - name: Commit All
      id: cmt
      uses: WCRP-CMIP/CMIP-LD/actions/commit_all@main
      with:
        message: "Automated update of JSONLD files, network and frames"

      # artifact on new version release required. 
      # if artifact, then release

        

    




    - name: cmt
      shell: bash
      if: env.needs_update != '0'
      run: |
        git config --global user.email "daniel.ellis@ext.esa.int"
        git config --global user.name "Daniel Ellis"
        git add -A 
        git commit -m 'demo'
        git push